# Generated by Django 2.1.3 on 2018-11-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mingle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('activitytime', models.DateTimeField(verbose_name='activity time')),
                ('location', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mingle.Activity')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mingle.User')),
            ],
        ),
    ]
